image: loyaltyone/docker-alpine-java-node:latest

stages:
- build
- deploy

build:
    stage: build
    script:
    - yum groupinstall "Development Tools"
    - export PATH=$(npm bin):$PATH
    - chmod a+x ./gradlew
    - ./gradlew -Pprod bootJar
    artifacts:
        paths:
        - build/libs/*.jar

production:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push
    only:
    - master
