image: loyaltyone/docker-alpine-java-node:latest

stages:
- build
- deploy

build:
    stage: build
    script:
    - apk update && apk add --virtual build-dependencies
    - apk --no-cache -q add build-base libgit2-dev
    - ln -s /usr/lib/libcurl.so.4 /usr/lib/libcurl-gnutls.so.4
    - apk add autoconf
    - export PATH=$(npm bin):$PATH
    - chmod a+x ./gradlew
    - ./gradlew -Pprod bootJar
    artifacts:
        paths:
        - build/libs/*.jar

production:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push
    only:
    - master
