image: java:8

stages:
- build
- deploy

build:
    stage: build
    script: ./gradlew bootJar
    artifacts:
        paths:
        - build/libs/*.jar

production:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push
    only:
    - master
