image: node:8-jessie

stages:
- build
- deploy

build:
    stage: build
    script:
    - echo 'deb http://deb.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
    - apt-get update && apt-get install -t jessie-backports openjdk-8-jdk ca-certificates-java --assume-yes
    - update-java-alternatives --list
    - update-java-alternatives --set java-1.8.0-openjdk-amd64
    - chmod a+x ./gradlew
    - export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk-amd64
    - find / -name tools.jar 2> /dev/null
    - ./gradlew -Pprod bootJar
    artifacts:
        paths:
        - build/libs/*.jar

production:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push
    only:
    - master
