image: node:8-jessie

stages:
- build
- deploy

build:
    stage: build
    script:
    - apt-get update && apt-get install -y --no-install-recommends bzip2 unzip xz-utils && rm -rf /var/lib/apt/lists/*
    - chmod a+x ./gradlew
    - export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
    - find / -name tools.jar 2> /dev/null
    - ./gradlew -Pprod bootJar
    artifacts:
        paths:
        - build/libs/*.jar

production:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push
    only:
    - master
