image: node:8-jessie

stages:
- build
- test
- deploy

before_script:
    - echo 'deb http://deb.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
    - apt-get update && apt-get install -t jessie-backports openjdk-8-jdk ca-certificates-java --assume-yes
    - chmod a+x ./gradlew
    - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

build jar:
    stage: build
    script:
    - ./gradlew -Pprod bootJar
    artifacts:
        paths:
        - build/libs/*.jar

test backend:
    stage: test
    script:
    - ./gradlew test

test frontend:
    stage: test
    script:
    - ./gradlew jsTest

review tslint:
    stage: test
    script:
    - npm install -g tslint
    - ./gradlew tsLint
    allow_failure: true

push to cloudfoundry:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push
    only:
    - master
