version: '2'
services:
    weightcars-app:
        image: weightcars
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://weightcars-postgresql:5432/weightCars
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    weightcars-postgresql:
        extends:
            file: postgresql.yml
            service: weightcars-postgresql
